#################################################################################################################################
#																																#
#	RLCraft Addon Plugin	    MC 1.17																					        #
#	Version 1.0	                Made by: Val_Mobile											                                    #
#																																#
#################################################################################################################################


#######################################
#          Messages                   #
#######################################

usage: "&cUsage: /rlcraft [reload, give [player] [item] ]"
reload: "&4[&cRLCRAFT&4] &aPlugin reloaded!"
nopermission: "&cYou do not have permission to do this!"
noOnlinePlayer: "&cThe specified player is not online!"
misspelledPlayer: "&cThe specified player's name was misspelled"
misspelledItemName: "&cYou mispelled the item!"

#######################################
#          Gameplay Features          #
#######################################

# Enable, disable, and customize any features
# Resource pack is disabled by default to allow for integration of it into
# your own custom server pack if needed
resourcePack:
  enabled: false
  url: "https://www.dropbox.com/s/sgru3wm4vj2tje5/RLCraft-Addons%20RP.zip?dl=1"
unlockRecipes: true
flintTools: true
noTreePunching: true
dragons:
  enabled: true
  # Chance the vanilla acid ball attack becomes a special attack instead
  # Make sure rates add up to 1.0
  breathAttackChance: 0.7
  explosionAttackChance: 0.2
  normalAttackChance: 0.1
  # Make sure rates add up to 1.0
  fireDragonRate: 0.4
  iceDragonRate: 0.3
  lightningDragonRate: 0.3
  # Recursive drop rates determine the number of bones and meat based on the number of scales dropped
  # More scales means less bones and more meat
  # Recommended since this is how the Ice and Fire mod determines drop rates for dragon loot
  # Disabling recursiveDropRates automatically enables specifiedDropRates
  recursiveDropRates:
    enabled: true
    minScales: 24
    maxScales: 48
    minBones: 6
    # The amount of dragon blood dropped is the amount of scales dropped times this multiplier
    # Ex: 48 scales * 0.2 bloodMultiplier = 9 dragon blood dropped (decimals are truncated)
    bloodMultiplier: 0.1
    fleshMultiplier: 0.6
  # Standard drop rates, rates for all loot must be specified
  specifiedDropRates:
    minScales: 24
    maxScales: 48
    minBones: 6
    maxBones: 54
    minBlood: 4
    maxBlood: 6
    minFlesh: 12
    maxFlesh: 36
seaSerpents:
  enabled: true
  minSerpentScales: 24
  maxSerpentScales: 48
  # Note that shiny scales only drop from regular guardians
  minShinyScales: 1
  maxShinyScales: 1
witherbones:
  enabled: true
  minBonesWither: 20
  maxBonesWither: 32
  minBonesWitherSkeleton: 1
  maxBonesWitherSkeleton: 1
baubles:
  enabled: true
  # Note 1.00 = 100%
  EnderDragonScale:
    dropChance: 1.00
    checkLooting: true
  ForbiddenFruit:
    dropChance: 0.025
    checkLooting: true
  RingOverclocking:
    dropChance: 0.03
    checkLooting: true
  Bezoar:
    dropChance: 0.05
    checkLooting: true
  Vitamins:
    dropChance: 1.00
    checkLooting: true

#######################################
#          Item Attributes            #
#######################################

# Customize the attributes of tools, weapons, and armor

tools:
  FlintPickaxe:
    attackDamage: 2.5
    attackSpeed: 2.5
  FlintAxe:
    attackDamage: 5.0
    attackSpeed: 1.0
  FlintShovel:
    attackDamage: 3.0
    attackSpeed: 2.4
  FlintHoe:
    attackDamage: 1.0
    attackSpeed: 2.6
  DragonBonePickaxe:
    attackDamage: 6.0
    attackSpeed: 1.2
  DragonBoneAxe:
    attackDamage: 10.0
    attackSpeed: 1.0
  DragonBoneShovel:
    attackDamage: 6.5
    attackSpeed: 1.0
  DragonBoneHoe:
    attackDamage: 1.0
    attackSpeed: 1.0
  FireDragonsteelPickaxe:
    attackDamage: 26.0
    attackSpeed: 1.2
  FireDragonsteelAxe:
    attackDamage: 30.0
    attackSpeed: 1.0
  FireDragonsteelShovel:
    attackDamage: 26.5
    attackSpeed: 1.0
  FireDragonsteelHoe:
    attackDamage: 2.0
    attackSpeed: 1.0
  IceDragonsteelPickaxe:
    attackDamage: 26.0
    attackSpeed: 1.2
  IceDragonsteelAxe:
    attackDamage: 30.0
    attackSpeed: 1.0
  IceDragonsteelShovel:
    attackDamage: 26.5
    attackSpeed: 1.0
  IceDragonsteelHoe:
    attackDamage: 2.0
    attackSpeed: 1.0
  LightningDragonsteelPickaxe:
    attackDamage: 26.0
    attackSpeed: 1.2
  LightningDragonsteelAxe:
    attackDamage: 30.0
    attackSpeed: 1.0
  LightningDragonsteelShovel:
    attackDamage: 26.5
    attackSpeed: 1.0
  LightningDragonsteelHoe:
    attackDamage: 2.0
    attackSpeed: 1.0

weapons:
  FlintKnife:
    attackDamage: 2.0
    attackSpeed: 3.0
  DragonBoneSword:
    attackDamage: 8.0
    attackSpeed: 1.6
  DragonBoneRapier:
    attackDamage: 4.5
    attackSpeed: 2.4
  DragonBoneKatana:
    attackDamage: 5.5
    attackSpeed: 2.0
  DragonBoneGreatsword:
    attackDamage: 14.0
    attackSpeed: 1.4
  DragonBoneLongsword:
    attackDamage: 10.5
    attackSpeed: 1.4
  DragonBoneSpear:
    attackDamage: 6.5
    attackSpeed: 1.4
  DragonBoneSaber:
    attackDamage: 6.5
    attackSpeed: 1.6
  DragonBoneBoomerang:
    attackDamage: 8.0
  DragonBoneDagger:
    attackDamage: 4.5
    attackSpeed: 2.5
  DragonBoneGlaive:
    attackDamage: 8.0
    attackSpeed: 1.0
  DragonBoneHalberd:
    attackDamage: 16.5
    attackSpeed: 1.2
  DragonBoneHammer:
    attackDamage: 10.0
    attackSpeed: 0.8
  DragonBoneJavelin:
    attackDamage: 3.5
    attackSpeed: 1.2
  DragonBoneLance:
    attackDamage: 8.0
    attackSpeed: 1.0
  DragonBoneMace:
    attackDamage: 8.0
    attackSpeed: 1.2
  DragonBonePike:
    attackDamage: 6.0
    attackSpeed: 1.4
  DragonBoneQuarterstaff:
    attackDamage: 5.5
    attackSpeed: 1.4
  DragonBoneThrowingAxe:
    attackDamage: 6.0
    attackSpeed: 0.9
  DragonBoneThrowingKnife:
    attackDamage: 3.5
    attackSpeed: 2.5
  DragonBoneWarhammer:
    attackDamage: 8.0
    attackSpeed: 1.1
  DragonBoneBattleaxe:
    attackDamage: 13.0
    attackSpeed: 1.0
  DragonBoneLongbow:
    attackDamageMultiplier: 1.75
    velocityMultiplier: 1.75
  DragonBoneBow:
    attackDamageMultiplier: 1.75
    velocityMultiplier: 1.75
  DragonBoneCrossbow:
    attackDamageMultiplier: 1.75
    velocityMultiplier: 1.75
  FlamedDragonBoneSword:
    attackDamage: 9.5
    attackSpeed: 1.6
  FlamedDragonBoneRapier:
    attackDamage: 5.25
    attackSpeed: 2.4
  FlamedDragonBoneKatana:
    attackDamage: 6.5
    attackSpeed: 2.0
  FlamedDragonBoneGreatsword:
    attackDamage: 17.0
    attackSpeed: 1.4
  FlamedDragonBoneLongsword:
    attackDamage: 12.75
    attackSpeed: 1.4
  FlamedDragonBoneSpear:
    attackDamage: 7.25
    attackSpeed: 1.4
  FlamedDragonBoneSaber:
    attackDamage: 7.25
    attackSpeed: 1.6
  FlamedDragonBoneBoomerang:
    attackDamage: 9.5
  FlamedDragonBoneDagger:
    attackDamage: 5.25
    attackSpeed: 2.5
  FlamedDragonBoneGlaive:
    attackDamage: 9.5
    attackSpeed: 1.0
  FlamedDragonBoneHalberd:
    attackDamage: 20.25
    attackSpeed: 1.2
  FlamedDragonBoneHammer:
    attackDamage: 11.5
    attackSpeed: 0.8
  FlamedDragonBoneJavelin:
    attackDamage: 4.25
    attackSpeed: 1.2
  FlamedDragonBoneLance:
    attackDamage: 9.5
    attackSpeed: 1.0
  FlamedDragonBoneMace:
    attackDamage: 9.5
    attackSpeed: 1.2
  FlamedDragonBonePike:
    attackDamage: 6.75
    attackSpeed: 1.4
  FlamedDragonBoneQuarterstaff:
    attackDamage: 7.0
    attackSpeed: 1.4
  FlamedDragonBoneThrowingAxe:
    attackDamage: 7.5
    attackSpeed: 0.9
  FlamedDragonBoneThrowingKnife:
    attackDamage: 4.25
    attackSpeed: 2.5
  FlamedDragonBoneWarhammer:
    attackDamage: 9.5
    attackSpeed: 1.1
  FlamedDragonBoneBattleaxe:
    attackDamage: 16.0
    attackSpeed: 1.0
  FlamedDragonBoneLongbow:
    attackDamageMultiplier: 2.0
    velocityMultiplier: 2.0
  FlamedDragonBoneCrossbow:
    attackDamageMultiplier: 2.0
    velocityMultiplier: 2.0
  IcedDragonBoneSword:
    attackDamage: 9.5
    attackSpeed: 1.6
  IcedDragonBoneRapier:
    attackDamage: 5.25
    attackSpeed: 2.4
  IcedDragonBoneKatana:
    attackDamage: 6.5
    attackSpeed: 2.0
  IcedDragonBoneGreatsword:
    attackDamage: 17.0
    attackSpeed: 1.4
  IcedDragonBoneLongsword:
    attackDamage: 12.75
    attackSpeed: 1.4
  IcedDragonBoneSpear:
    attackDamage: 7.25
    attackSpeed: 1.4
  IcedDragonBoneSaber:
    attackDamage: 7.25
    attackSpeed: 1.6
  IcedDragonBoneBoomerang:
    attackDamage: 9.5
  IcedDragonBoneDagger:
    attackDamage: 5.25
    attackSpeed: 2.5
  IcedDragonBoneGlaive:
    attackDamage: 9.5
    attackSpeed: 1.0
  IcedDragonBoneHalberd:
    attackDamage: 20.25
    attackSpeed: 1.2
  IcedDragonBoneHammer:
    attackDamage: 11.5
    attackSpeed: 0.8
  IcedDragonBoneJavelin:
    attackDamage: 4.25
    attackSpeed: 1.2
  IcedDragonBoneLance:
    attackDamage: 9.5
    attackSpeed: 1.0
  IcedDragonBoneMace:
    attackDamage: 9.5
    attackSpeed: 1.2
  IcedDragonBonePike:
    attackDamage: 6.75
    attackSpeed: 1.4
  IcedDragonBoneQuarterstaff:
    attackDamage: 7.0
    attackSpeed: 1.4
  IcedDragonBoneThrowingAxe:
    attackDamage: 7.5
    attackSpeed: 0.9
  IcedDragonBoneThrowingKnife:
    attackDamage: 4.25
    attackSpeed: 2.5
  IcedDragonBoneWarhammer:
    attackDamage: 9.5
    attackSpeed: 1.1
  IcedDragonBoneBattleaxe:
    attackDamage: 16.0
    attackSpeed: 1.0
  IcedDragonBoneLongbow:
    attackDamageMultiplier: 2.0
    velocityMultiplier: 2.0
  IcedDragonBoneCrossbow:
    attackDamageMultiplier: 2.0
    velocityMultiplier: 2.0
  LightningDragonBoneSword:
    attackDamage: 9.5
    attackSpeed: 1.6
  LightningDragonBoneRapier:
    attackDamage: 5.25
    attackSpeed: 2.4
  LightningDragonBoneKatana:
    attackDamage: 6.5
    attackSpeed: 2.0
  LightningDragonBoneGreatsword:
    attackDamage: 17.0
    attackSpeed: 1.4
  LightningDragonBoneLongsword:
    attackDamage: 12.75
    attackSpeed: 1.4
  LightningDragonBoneSpear:
    attackDamage: 7.25
    attackSpeed: 1.4
  LightningDragonBoneSaber:
    attackDamage: 7.25
    attackSpeed: 1.6
  LightningDragonBoneBoomerang:
    attackDamage: 9.5
  LightningDragonBoneDagger:
    attackDamage: 5.25
    attackSpeed: 2.5
  LightningDragonBoneGlaive:
    attackDamage: 9.5
    attackSpeed: 1.0
  LightningDragonBoneHalberd:
    attackDamage: 20.25
    attackSpeed: 1.2
  LightningragonBoneHammer:
    attackDamage: 11.5
    attackSpeed: 0.8
  LightningDragonBoneJavelin:
    attackDamage: 4.25
    attackSpeed: 1.2
  LightningDragonBoneLance:
    attackDamage: 9.5
    attackSpeed: 1.0
  LightningDragonBoneMace:
    attackDamage: 9.5
    attackSpeed: 1.2
  LightningDragonBonePike:
    attackDamage: 6.75
    attackSpeed: 1.4
  LightningDragonBoneQuarterstaff:
    attackDamage: 7.0
    attackSpeed: 1.4
  LightningDragonBoneThrowingAxe:
    attackDamage: 7.5
    attackSpeed: 0.9
  LightningDragonBoneThrowingKnife:
    attackDamage: 4.25
    attackSpeed: 2.5
  LightningDragonBoneWarhammer:
    attackDamage: 9.5
    attackSpeed: 1.1
  LightningDragonBoneBattleaxe:
    attackDamage: 16.0
    attackSpeed: 1.0
  LightningDragonBoneLongbow:
    attackDamageMultiplier: 2.0
    velocityMultiplier: 2.0
  LightningDragonBoneCrossbow:
    attackDamageMultiplier: 2.0
    velocityMultiplier: 2.0
  FireDragonsteelSword:
    attackDamage: 25.0
    attackSpeed: 1.6
  FireDragonsteelRapier:
    attackDamage: 13.0
    attackSpeed: 2.4
  FireDragonsteelKatana:
    attackDamage: 14.0
    attackSpeed: 2.0
  FireDragonsteelGreatsword:
    attackDamage: 48.0
    attackSpeed: 1.4
  FireDragonsteelLongsword:
    attackDamage: 36.0
    attackSpeed: 1.4
  FireDragonsteelSpear:
    attackDamage: 15.0
    attackSpeed: 1.4
  FireDragonsteelSaber:
    attackDamage: 15.0
    attackSpeed: 1.6
  FireDragonsteelBoomerang:
    attackDamage: 25.0
  FireDragonsteelDagger:
    attackDamage: 13.0
    attackSpeed: 2.5
  FireDragonsteelGlaive:
    attackDamage: 25.0
    attackSpeed: 1.0
  FireDragonsteelHalberd:
    attackDamage: 59.0
    attackSpeed: 1.2
  FireDragonsteelHammer:
    attackDamage: 27.0
    attackSpeed: 0.8
  FireDragonsteelJavelin:
    attackDamage: 12.0
    attackSpeed: 1.2
  FireDragonsteelLance:
    attackDamage: 25.0
    attackSpeed: 1.0
  FireDragonsteelMace:
    attackDamage: 25.0
    attackSpeed: 1.2
  FireDragonsteelPike:
    attackDamage: 14.5
    attackSpeed: 1.4
  FireDragonsteelQuarterstaff:
    attackDamage: 22.5
    attackSpeed: 1.4
  FireDragonsteelThrowingAxe:
    attackDamage: 23.0
    attackSpeed: 0.9
  FireDragonsteelThrowingKnife:
    attackDamage: 12.0
    attackSpeed: 2.5
  FireDragonsteelWarhammer:
    attackDamage: 25.0
    attackSpeed: 1.1
  FireDragonsteelBattleaxe:
    attackDamage: 47.0
    attackSpeed: 1.0
  FireDragonsteelLongbow:
    attackDamageMultiplier: 3.0
    velocityMultiplier: 3.0
  FireDragonsteelCrossbow:
    attackDamageMultiplier: 3.0
    velocityMultiplier: 3.0
  IceDragonsteelSword:
    attackDamage: 25.0
    attackSpeed: 1.6
  IceDragonsteelRapier:
    attackDamage: 13.0
    attackSpeed: 2.4
  IceDragonsteelKatana:
    attackDamage: 14.0
    attackSpeed: 2.0
  IceDragonsteelGreatsword:
    attackDamage: 48.0
    attackSpeed: 1.4
  IceDragonsteelLongsword:
    attackDamage: 36.0
    attackSpeed: 1.4
  IceDragonsteelSpear:
    attackDamage: 15.0
    attackSpeed: 1.4
  IceDragonsteelSaber:
    attackDamage: 15.0
    attackSpeed: 1.6
  IceDragonsteelBoomerang:
    attackDamage: 25.0
  IceDragonsteelDagger:
    attackDamage: 13.0
    attackSpeed: 2.5
  IceDragonsteelGlaive:
    attackDamage: 25.0
    attackSpeed: 1.0
  IceDragonsteelHalberd:
    attackDamage: 59.0
    attackSpeed: 1.2
  IceDragonsteelHammer:
    attackDamage: 27.0
    attackSpeed: 0.8
  IceDragonsteelJavelin:
    attackDamage: 12.0
    attackSpeed: 1.2
  IceDragonsteelLance:
    attackDamage: 25.0
    attackSpeed: 1.0
  IceDragonsteelMace:
    attackDamage: 25.0
    attackSpeed: 1.2
  IceDragonsteelPike:
    attackDamage: 14.5
    attackSpeed: 1.4
  IceDragonsteelQuarterstaff:
    attackDamage: 22.5
    attackSpeed: 1.4
  IceDragonsteelThrowingAxe:
    attackDamage: 23.0
    attackSpeed: 0.9
  IceDragonsteelThrowingKnife:
    attackDamage: 12.0
    attackSpeed: 2.5
  IceDragonsteelWarhammer:
    attackDamage: 25.0
    attackSpeed: 1.1
  IceDragonsteelBattleaxe:
    attackDamage: 47.0
    attackSpeed: 1.0
  IceDragonsteelLongbow:
    attackDamageMultiplier: 3.0
    velocityMultiplier: 3.0
  IceDragonsteelCrossbow:
    attackDamageMultiplier: 3.0
    velocityMultiplier: 3.0
  LightningDragonsteelSword:
    attackDamage: 25.0
    attackSpeed: 1.6
  LightningDragonsteelRapier:
    attackDamage: 13.0
    attackSpeed: 2.4
  LightningDragonsteelKatana:
    attackDamage: 14.0
    attackSpeed: 2.0
  LightningDragonsteelGreatsword:
    attackDamage: 48.0
    attackSpeed: 1.4
  LightningDragonsteelLongsword:
    attackDamage: 36.0
    attackSpeed: 1.4
  LightningDragonsteelSpear:
    attackDamage: 15.0
    attackSpeed: 1.4
  LightningDragonsteelSaber:
    attackDamage: 15.0
    attackSpeed: 1.6
  LightningDragonsteelBoomerang:
    attackDamage: 25.0
  LightningDragonsteelDagger:
    attackDamage: 13.0
    attackSpeed: 2.5
  LightningDragonsteelGlaive:
    attackDamage: 25.0
    attackSpeed: 1.0
  LightningDragonsteelHalberd:
    attackDamage: 59.0
    attackSpeed: 1.2
  LightningDragonsteelHammer:
    attackDamage: 27.0
    attackSpeed: 0.8
  LightningDragonsteelJavelin:
    attackDamage: 12.0
    attackSpeed: 1.2
  LightningDragonsteelLance:
    attackDamage: 25.0
    attackSpeed: 1.0
  LightningDragonsteelMace:
    attackDamage: 25.0
    attackSpeed: 1.2
  LightningDragonsteelPike:
    attackDamage: 14.5
    attackSpeed: 1.4
  LightningDragonsteelQuarterstaff:
    attackDamage: 22.5
    attackSpeed: 1.4
  LightningDragonsteelThrowingAxe:
    attackDamage: 23.0
    attackSpeed: 0.9
  LightningDragonsteelThrowingKnife:
    attackDamage: 12.0
    attackSpeed: 2.5
  LightningDragonsteelWarhammer:
    attackDamage: 25.0
    attackSpeed: 1.1
  LightningDragonsteelBattleaxe:
    attackDamage: 47.0
    attackSpeed: 1.0
  LightningDragonsteelLongbow:
    attackDamageMultiplier: 3.0
    velocityMultiplier: 3.0
  LightningDragonsteelCrossbow:
    attackDamageMultiplier: 3.0
    velocityMultiplier: 3.0
armor:
  DragonScaleHelmet:
    armor: 5.0
    toughness: 2.0
  DragonScaleChestplate:
    armor: 9.0
    toughness: 2.0
  DragonScaleLeggings:
    armor: 7.0
    toughness: 2.0
  DragonScaleBoots:
    armor: 5.0
    toughness: 2.0
  FireDragonsteelHelmet:
    armor: 7.0
    toughness: 6.0
  FireDragonsteelChestplate:
    armor: 12.0
    toughness: 6.0
  FireDragonsteelLeggings:
    armor: 9.0
    toughness: 6.0
  FireDragonsteelBoots:
    armor: 6.0
    toughness: 6.0
  IceDragonsteelHelmet:
    armor: 7.0
    toughness: 6.0
  IceDragonsteelChestplate:
    armor: 12.0
    toughness: 6.0
  IceDragonsteelLeggings:
    armor: 9.0
    toughness: 6.0
  IceDragonsteelBoots:
    armor: 6.0
    toughness: 6.0
  LightningDragonsteelHelmet:
    armor: 7.0
    toughness: 6.0
  LightningDragonsteelChestplate:
    armor: 12.0
    toughness: 6.0
  LightningDragonsteelLeggings:
    armor: 9.0
    toughness: 6.0
  LightningDragonsteelBoots:
    armor: 6.0
    toughness: 6.0
  TideGuardianHelmet:
    armor: 4.0
    toughness: 2.5
  TideGuardianChestplate:
    armor: 7.0
    toughness: 2.5
  TideGuardianLeggings:
    armor: 8.0
    toughness: 2.5
  TideGuardianBoots:
    armor: 4.0
    toughness: 2.5