#################################################################################################################################
#																																#
#	RLCraft Addon Plugin	    MC 1.17																					        #
#	Version 1.0	                Made by: Val_Mobile											                                    #
#																																#
#################################################################################################################################


#######################################
#          Messages                   #
#######################################

usage: "&cUsage: /rlcraft [reload, give [player] [item] ]"
reload: "&4[&cRLCRAFT&4] &aPlugin reloaded!"
nopermission: "&cYou do not have permission to do this!"
noOnlinePlayer: "&cThe specified player is not online!"
misspelledPlayer: "&cThe specified player's name was misspelled"
misspelledItemName: "&cYou mispelled the item!"

#######################################
#          Gameplay Features          #
#######################################

# Enable and disable features to your liking
# There are 5 other configs to customize the individual details of each feature
# Resource pack is disabled by default to allow for integration of it into
# your own custom server pack if needed
ResourcePack:
  Enabled: false
  URL: "https://www.dropbox.com/s/sgru3wm4vj2tje5/RLCraft-Addons%20RP.zip?dl=1"
UnlockRecipes: true
FlintTools: true
NoTreePunching: true
Dragons: true
SeaSerpents: true
Witherbones: true
Baubles: true