main: me.val_mobile.realisticsurvival.RealisticSurvivalPlugin
name: RealisticSurvival
version: ${project.version}
author: Val_Mobile
api-version: 1.17
softdepend: [RealisticSeasons]

commands:
  RealisticSurvival:
    description: The RealisticSurvival command

permissions:
  realisticsurvival.toughasnails.resistance.cold:
    description: Grants the player immunity from getting cold
    default: op
  realisticsurvival.toughasnails.resistance.hot:
    description: Grants the player immunity from getting hot
    default: op
  realisticsurvival.toughasnails.resistance.dehydration:
    description: Grants the player immunity to the health effects of dehydration
    default: op
  realisticsurvival.toughasnails.resistance.hypothermia:
    description: Grants the player immunity to the health effects of cold temperature
    default: op
  realisticsurvival.toughasnails.resistance.hyperthermia:
    description: Grants the player immunity to health effects of high temperature
    default: op
  realisticsurvival.toughasnails.resistance.burning:
    description: Grants the player immunity to the visual effects of high temperature
    default: op
  realisticsurvival.toughasnails.resistance.freezing:
    description: Grants the player immunity to the visual effects of cold temperature
    default: op
  realisticsurvival.toughasnails.resistance.*:
    description: Wildcard permission
    default: op
    children:
      realisticsurvival.toughasnails.resistance.thirst: true
      realisticsurvival.toughasnails.resistance.cold: true
      realisticsurvival.toughasnails.resistance.hot: true
      realisticsurvival.toughasnails.resistance.hypothermia: true
      realisticsurvival.toughasnails.resistance.hyperthermia: true
      realisticsurvival.toughasnails.resistance.burning: true
      realisticsurvival.toughasnails.resistance.freezing: true
  realisticsurvival.command.give:
    description: Allows users to give themselves items from the Realistic-Survival plugin
    default: op
  realisticsurvival.command.reload:
    description: Allows users to reload the Realistic-Survival plugin
    default: op
  realisticsurvival.command.thirst:
    description: Allows users to change the thirst level of other players
    default: op
  realisticsurvival.command.temperature:
    description: Allows users to change the temperature level of other players
    default: op
  realisticsurvival.command.*:
    description: Wildcard permission
    default: op
    children:
      realisticsurvival.command.give: true
      realisticsurvival.command.reload: true
      realisticsurvival.command.thirst: true
      realisticsurvival.command.temperature: true