main: me.val_mobile.realisticsurvival.RealisticSurvivalPlugin
name: RealisticSurvival
version: 1.2.3-DEV-3
author: Val_Mobile
description: A Spigot plugin that aims to increase the difficulty of normal vanilla Minecraft
website: https://www.spigotmc.org/resources/realistic-survival-1-17-temperature-thirst-baubles.93795
api-version: 1.16
softdepend: [RealisticSeasons]

commands:
  RealisticSurvival:
    description: The home command of the Realistic Survival plugin
    usage: /realisticsurvival
    aliases: [rsv]
    permission: realisticsurvival.command.*

permissions:
  realisticsurvival.iceandfire.resistance.sirenvisual:
    description: Prevents the player's screen from changing due to sirens
    default: not op
  realisticsurvival.iceandfire.resistance.*:
    description: Wildcard permission
    default: not op
    children:
      realisticsurvival.iceandfire.resistance.sirenvisual: true
  realisticsurvival.toughasnails.resistance.cold:
    description: Prevents the player from getting cold
    default: not op
  realisticsurvival.toughasnails.resistance.colddamage:
    description: Prevents the player from taking damage due to hypothermia
    default: not op
  realisticsurvival.toughasnails.resistance.coldpotioneffects:
    description: Prevents the player from receiving status effects due to hypothermia
    default: not op
  realisticsurvival.toughasnails.resistance.coldvisual:
    description: Prevents the player's screen from freezing due to hypothermia
    default: not op
  realisticsurvival.toughasnails.resistance.hot:
    description: Prevents the player from getting hot
    default: not op
  realisticsurvival.toughasnails.resistance.hotdamage:
    description: Prevents the player from taking damage due to hyperthermia
    default: not op
  realisticsurvival.toughasnails.resistance.hotcombustion:
    description: Prevents the player from being ignited due to hyperthermia
    default: not op
  realisticsurvival.toughasnails.resistance.hotpotioneffects:
    description: Prevents the player from receiving status effects due to hyperthermia
    default: not op
  realisticsurvival.toughasnails.resistance.hotvisual:
    description: Prevents the player's screen from burning due to hypothermia
    default: not op
  realisticsurvival.toughasnails.resistance.thirst:
    description: Prevents the player from getting thirsty
    default: not op
  realisticsurvival.toughasnails.resistance.thirstdamage:
    description: Prevents the player from taking damage due to dehydration
    default: not op
  realisticsurvival.toughasnails.resistance.thirstpotioneffects:
    description: Prevents the player from receiving status effects due to dehydration
    default: not op
  realisticsurvival.toughasnails.resistance.thirstvisual:
    description: Prevents the player's screen from changing due to dehydration
    default: not op
  realisticsurvival.toughasnails.resistance.*:
    description: Wildcard permission
    default: not op
    children:
      realisticsurvival.toughasnails.resistance.cold: true
      realisticsurvival.toughasnails.resistance.colddamage: true
      realisticsurvival.toughasnails.resistance.coldpotioneffects: true
      realisticsurvival.toughasnails.resistance.coldvisual: true
      realisticsurvival.toughasnails.resistance.hot: true
      realisticsurvival.toughasnails.resistance.hotdamage: true
      realisticsurvival.toughasnails.resistance.hotpotioneffects: true
      realisticsurvival.toughasnails.resistance.hotvisual: true
      realisticsurvival.toughasnails.resistance.thirst: true
      realisticsurvival.toughasnails.resistance.thirstdamage: true
      realisticsurvival.toughasnails.resistance.thirstpotioneffects: true
      realisticsurvival.toughasnails.resistance.thirstvisual: true
  realisticsurvival.command.give:
    description: Allows users to give themselves items from the plugin
    default: op
  realisticsurvival.command.spawnitem:
    description: Allows users to spawn items from the plugin
    default: op
  realisticsurvival.command.spawnmob:
    description: Allows users to spawn mobs from the plugin
    default: op
  realisticsurvival.command.reload:
    description: Allows users to reload the plugin
    default: op
  realisticsurvival.command.thirst:
    description: Allows users to change the thirst of other players
    default: op
  realisticsurvival.command.temperature:
    description: Allows users to change the temperature of other players
    default: op
  realisticsurvival.command.resetitem:
    description: Allows users to reset their item to use in recipes
    default: op
  realisticsurvival.command.updateitem:
    description: Allows users to update their item
    default: op
  realisticsurvival.command.help:
    description: Allows users to access the help command
    default: op
  realisticsurvival.command.version:
    description: Allows users to access the plugin version
    default: op
  realisticsurvival.command.*:
    description: Wildcard permission
    default: op
    children:
      realisticsurvival.command.give: true
      realisticsurvival.command.spawnitem: true
      realisticsurvival.command.spawnmob: true
      realisticsurvival.command.reload: true
      realisticsurvival.command.thirst: true
      realisticsurvival.command.temperature: true
      realisticsurvival.command.resetitem: true
      realisticsurvival.command.updateitem: true
      realisticsurvival.command.help: true
      realisticsurvival.command.version: true